Bazar.web/Controllers/HomeController.cs
using Bazar.Services;
using Bazar.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bazar.web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            IndexModel model = new IndexModel();
            model.Featuredcategories = CategoryServices.Instance.GetFeaturedCats();
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Bazar.web/Controllers/PrductWidgetController.cs
using Bazar.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bazar.Services;

namespace Bazar.web.Controllers
{
    public class PrductWidgetController : Controller
    {
        // GET: PrductWidget
        public ActionResult Products(bool isLatestPro)
        {
            WidgetPro model = new WidgetPro();
            model.IsLatestPRo = isLatestPro;
            if (isLatestPro)
            {
                model.Products = ProductServices.Instance.GetLatestPros(4);
            }
            else
            {
                model.Products = ProductServices.Instance.GetLatestPros(8);
            }
            return PartialView(model);
        }
    }
}

Bazar.web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Bazar.web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Bazar.web/Views/Home/Index.cshtml
@model Bazar.web.Models.IndexModel
@{
    ViewBag.Title = "Home";
    var firstcat = Model.Featuredcategories[0];
    var seccat = Model.Featuredcategories[1];
    var thirdcat = Model.Featuredcategories[2];
    var fourthcat = Model.Featuredcategories[3];
}
<section class="flat-row row-image-box">
    <div class="container">
        <div class="title-section margin-bottom-52">
            <h2 class="title">
                All Categories
            </h2>
        </div>
        <div class="row gutter-10">
            <div class="col-sm-6 col-md-4">
                <div class="flat-image-box style-1 data-effect div-h22 clearfix">
                    <div class="item data-effect-item">
                        <div class="inner">
                            @if (firstcat != null)
                            {
                                <div class="thumb">
                                    <img src="@firstcat.imageUrl" alt="Image">
                                    <div class="elm-btn">
                                        <a href="#" class="themesflat-button bg-white width-150">@firstcat.name</a>
                                    </div>
                                    <div class="overlay-effect bg-color-1"></div>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div><!-- /.col-md-4 -->
            <div class="col-sm-6 col-md-4">
                <div class="flat-image-box style-1 row2 data-effect clearfix">
                    <div class="item data-effect-item">
                        <div class="inner">
                        @if (seccat != null)
                        {
                            <div class="thumb">
                                <img src="@seccat.imageUrl" alt="Image">
                                <div class="elm-btn">
                                    <a href="#" class="themesflat-button bg-white width-150">@seccat.name</a>
                                </div>
                                <div class="overlay-effect bg-color-1"></div>
                            </div>
                        }

                        </div>
                    </div>

                    <div class="item data-effect-item">
                        <div class="inner">
                        @if (thirdcat != null)
                        {
                            <div class="thumb">
                                <img src="@thirdcat.imageUrl" alt="Image">
                                <div class="elm-btn">
                                    <a href="#" class="themesflat-button bg-white width-150">@thirdcat.name</a>
                                </div>
                                <div class="overlay-effect bg-color-1"></div>
                            </div>
                        }
                        </div>
                    </div>
                </div>
            </div><!-- /.col-md-4 -->
            <div class="col-sm-6 col-md-4">
                <div class="flat-image-box style-1 data-effect div-h20 clearfix">
                    <div class="item data-effect-item">
                        <div class="inner">
                            @if (fourthcat != null)
                            {
                            <div class="thumb">
                                <img src="@fourthcat.imageUrl" alt="Image">
                                <div class="elm-btn">
                                    <a href="#" class="themesflat-button bg-white width-150">@fourthcat.name</a>
                                </div>
                                <div class="overlay-effect bg-color-1"></div>
                            </div>
                            }
                        </div>
                    </div>
                </div>
            </div><!-- /.col-md-4 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section>
<!-- END IMAGE BOX -->
<!-- PRODUCT NEW -->
<section class="flat-row row-product-new">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section margin-bottom-52">
                    <h2 class="title">
                        New Product
                    </h2>
                </div>
                @{ Html.RenderAction("Products", "PrductWidget", new { isLatestPro = true });}
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</section>
<!-- END PRODUCT NEW -->
<!-- ANIMATION BOX -->
<section class="flat-row row-animation-box bg-section row-1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="flat-animation-block">
                    <div class="title-section width-before-17 bg-before-white margin-bottom-14">
                        <div class="sup-title"><span>NEW TREND 2018</span></div>
                        <h2 class="title font-size-52 line-height-76">Women‘s Collection</h2>
                        <div class="sub-title"><span>Big Sale of this Week</span></div>
                    </div>
                    <div class="elm-btn text-center">
                        <a href="#" class="themesflat-button bg-accent has-padding-36">Shop Now</a>
                    </div>
                </div><!-- /.flat-animation-block -->
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</section>
<!-- END ANIMATION BOX -->
<!-- PRODUCT -->
<section class="flat-row row-product-project style-1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section margin-bottom-41">
                    <h2 class="title">Best Sale</h2>
                </div>
                @{ Html.RenderAction("Products", "PrductWidget", new { isLatestPro = false });}
            </div>
        </div>
    </div>
</section>
<!-- END PRODUCT -->
<!-- ICON BOX -->
<section class="flat-row row-icon-box bg-section bg-color-f5f">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="flat-icon-box icon-top style-1 clearfix text-center">
                    <div class="inner no-margin">
                        <div class="icon-wrap">
                            <i class="fa fa-truck"></i>
                        </div>
                        <div class="text-wrap">
                            <h5 class="heading"><a href="#">Free Shipping</a></h5>
                            <p class="desc">Free Shipping on order over $99</p>
                        </div>
                    </div>
                </div>
            </div><!-- /.col-md-3 -->
            <div class="col-md-3">
                <div class="flat-icon-box icon-top style-1 clearfix text-center">
                    <div class="inner">
                        <div class="icon-wrap">
                            <i class="fa fa-money"></i>
                        </div>
                        <div class="text-wrap">
                            <h5 class="heading"><a href="#">Cash On Delivery</a></h5>
                            <p class="desc">The Internet Trend To Repeat</p>
                        </div>
                    </div>
                </div>
            </div><!-- /.col-md-3 -->
            <div class="col-md-3">
                <div class="flat-icon-box icon-top style-1 clearfix text-center">
                    <div class="inner">
                        <div class="icon-wrap">
                            <i class="fa fa-gift"></i>
                        </div>
                        <div class="text-wrap">
                            <h5 class="heading"><a href="#">Gift For All</a></h5>
                            <p class="desc">Receive Gift When Subscribe</p>
                        </div>
                    </div>
                </div>
            </div><!-- /.col-md-3 -->
            <div class="col-md-3">
                <div class="flat-icon-box icon-top style-1 clearfix text-center">
                    <div class="inner">
                        <div class="icon-wrap">
                            <i class="fa fa-clock-o"></i>
                        </div>
                        <div class="text-wrap">
                            <h5 class="heading"><a href="#">Opening All Week</a></h5>
                            <p class="desc">6.00 am - 17.00pm</p>
                        </div>
                    </div>
                </div>
            </div><!-- /.col-md-3 -->
        </div>
    </div>
</section>
<!-- END ICON BOX -->