Bazar.web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bazar.Entity;
using Bazar.Services;
using Bazar.web.Models;

namespace Bazar.web.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        { 
            return View();
        }
        public ActionResult ProductTable(string search, int?PageNo)
        {
            ProductData model = new ProductData();
            model.searchTerm = search;
            PageNo = PageNo.HasValue ? PageNo.Value > 0 ? PageNo.Value : 1 : 1;
            var totalrecords = ProductServices.Instance.GetProCount(search);
            model.products = ProductServices.Instance.GetPros(PageNo.Value, search);
            if (model.products != null)
            {
                model.pager = new Pager(totalrecords, PageNo, 5);
                return PartialView(model);
            }
            else
            {
            return HttpNotFound();
            }

        }
        [HttpGet]
        public ActionResult Create()
        {
            
            var cat = CategoryServices.Instance.GetCats();
            return PartialView(cat);
        }
        [HttpPost]
        public ActionResult Create(productView pro)
        {

            Product newProduct = new Product();
            newProduct.name = pro.name;
            newProduct.imageUrl = pro.imageUrl;
            newProduct.price = pro.price;
            newProduct.description = pro.description;
            newProduct.IsFeatured = pro.IsFeatured;
            newProduct.category = CategoryServices.Instance.GetCat(pro.category);
            ProductServices.Instance.SavePro(newProduct);
            return RedirectToAction("ProductTable");
        }
        public ActionResult Edit(int Id)
        {
            
            ViewBag.allCat = CategoryServices.Instance.GetCats();
            var pro = ProductServices.Instance.GetPro(Id);
            return PartialView(pro);
        }
        [HttpPost]
        public ActionResult Edit(productView pro)
        {
            
            Product newProduct = new Product();
            newProduct.id = pro.id;
            newProduct.name = pro.name;
            newProduct.imageUrl = pro.imageUrl;
            newProduct.price = pro.price;
            newProduct.description = pro.description;
            newProduct.IsFeatured = pro.IsFeatured;
            newProduct.category = CategoryServices.Instance.GetCat(pro.category);
            ProductServices.Instance.UpdatePro(newProduct);
            return RedirectToAction("ProductTable");
        }
        [HttpPost]
        public ActionResult Delete(int Id)
        {
            ProductServices.Instance.DeletePro(ProductServices.Instance.GetPro(Id));
            return RedirectToAction("ProductTable");
        }
        public ActionResult details(int Id)
        {
            ProDetails pro = new ProDetails();
            pro.product = ProductServices.Instance.GetPro(Id);
            return View(pro);
        }
    }
}

Bazar.web/Controllers/ShopController.cs
using Bazar.Services;
using Bazar.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace Bazar.web.Controllers
{
    public class ShopController : Controller
    {
        public ActionResult Index(string searchTerm,int? minPrice,int? maxPrice,int? catId, int? sort)
        {
            shopModelAll Model = new shopModelAll();
            Model.Fcategories = CategoryServices.Instance.GetFeaturedCats();
            Model.maxPrice = ProductServices.Instance.GetMaxPrice();
            Model.Products = ProductServices.Instance.searchPro(searchTerm, minPrice, maxPrice, catId,sort);
            Model.sort = sort;
            return View(Model);
        }
        public ActionResult FilterIndex(string searchTerm, int? minPrice, int? maxPrice, int? catId, int? sort)
        {
            FilterShop Model = new FilterShop();
            Model.products = ProductServices.Instance.searchPro(searchTerm, minPrice, maxPrice, catId, sort);
            return PartialView(Model);
        }
        public ActionResult CheckOut()
        {
            shopModel model = new shopModel();
            var cookiesOfCart = Request.Cookies["cartProducts"];
            if (cookiesOfCart != null)
            {
                var proIds = cookiesOfCart.Value.Split('-').Select(x => int.Parse(x)).ToList();
                model.CartProduct = ProductServices.Instance.GetPros(proIds);
                model.CartProductIds = proIds;
            }
            return View(model);
        }
    }
}

Bazar.web/Views/Shop/CheckOut.cshtml
@model Bazar.web.Models.shopModel
@if(Model!=null){
    if (Model.CartProduct != null && Model.CartProduct.Count > 0)
    {
        <div>
            @foreach(var product in Model.CartProduct)
            {
                var productQuan = Model.CartProductIds.Where(x => x == product.id).Count();
                <div>
                    Name: @product.name , Price: @product.price , Quantity: @productQuan, Total: @(product.price*productQuan),
                </div>
            }
        </div>
        <div>
            Total Bill: @Model.CartProduct.Sum(pro => pro.price * Model.CartProductIds.Where(x => x == pro.id).Count());
        </div>
    }
}

Bazar.web/Views/Shop/FilterIndex.cshtml
@model Bazar.web.Models.FilterShop
    @{ 
        var defaultImg = "/Content/images/placeholder-image.png";
    }
<div class="product-content product-threecolumn product-slidebar clearfix">
    <ul class="product style2 sd1">
        @foreach (var product in Model.products)
        {
            var ImgUrl = string.IsNullOrEmpty(product.imageUrl) ? defaultImg : product.imageUrl;
            <li class="product-item">
                <div class="product-thumb clearfix">
                    <a href="@Url.Action("details","Product",new { Id=product.id})">
                        <img src="@ImgUrl" alt="image">
                    </a>
                    <span class="new">New</span>
                </div>
                <div class="product-info clearfix">
                    <span class="product-title">@product.name</span>
                    <div class="price">
                        <ins>
                            <span class="amount">₹@product.price</span>
                        </ins>
                    </div>
                </div>
                <div class="add-to-cart text-center">
                    <a href="#">ADD TO CART</a>
                </div>
                <a href="#" class="like"><i class="fa fa-heart-o"></i></a>
            </li>
        }
    </ul><!-- /.product -->
</div><!-- /.product-content -->

Bazar.web/Views/Shop/Index.cshtml
@using Bazar.Services.Code
@using Bazar.web.Models
@model Bazar.web.Models.shopModelAll
@{
    ViewBag.Title = "SHOP";
}
<div class="page-title parallax parallax1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title-heading">
                    <h1 class="title">Slidebar Shop</h1>
                </div><!-- /.page-title-heading -->
                <div class="breadcrumbs">
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li><a href="shop-3col.html">Shop</a></li>
                        <li><a href="shop-3col-slide.html">Slidebarshop</a></li>
                    </ul>
                </div><!-- /.breadcrumbs -->
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</div><!-- /.page-title -->
<section class="flat-row main-shop shop-slidebar">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="sidebar slidebar-shop">
                    <div class="widget widget-search">
                        <form role="search" method="get" class="search-form" action="@Url.Action("Index","Shop")">
                            <label>
                                <input type="search" class="search-field" placeholder="Search …" value="" name="searchTerm">
                            </label>
                            <input type="submit" class="search-submit" value="Search">
                        </form>
                    </div><!-- /.widget-search -->
                    <div class="widget widget-sort-by">
                        <h5 class="widget-title">
                            Sort By
                        </h5>
                        <ul>
                            <li><a href="@Url.Action("Index","Shop",new {sort=(int)sortEnums.Default})" class="@(Model.sort.HasValue?Model.sort.Value==(int)sortEnums.Default?"active":string.Empty:string.Empty)">Default - Newness</a></li>
                            <li><a href="@Url.Action("Index","Shop",new {sort=(int)sortEnums.popularity})" class="@(Model.sort.HasValue?Model.sort.Value==(int)sortEnums.popularity?"active":string.Empty:string.Empty)">Popularity</a></li>
                            <li><a href="@Url.Action("Index","Shop",new {sort=(int)sortEnums.lowTohigh})" class="@(Model.sort.HasValue?Model.sort.Value==(int)sortEnums.lowTohigh?"active":string.Empty:string.Empty)">Price: low to high</a></li>
                            <li><a href="@Url.Action("Index","Shop",new {sort=(int)sortEnums.HighToLow})" class="@(Model.sort.HasValue?Model.sort.Value==(int)sortEnums.HighToLow?"active":string.Empty:string.Empty)">Price: high to low</a></li>
                        </ul>
                    </div><!-- /.widget-sort-by -->
                    <div class="widget widget-price">
                        <h5 class="widget-title">Filter by price</h5>
                        <div class="price-filter">
                            <div id="slide-range"></div>
                            <p class="amount">
                                Price: <input type="text" id="amount" disabled="">
                            </p>
                        </div>
                    </div>
                    <div class="widget widget_tag">
                        <h5 class="widget-title">
                            Featured Categories
                        </h5>
                        <div class="tag-list">
                            @foreach (var category in Model.Fcategories)
                            {
                                <a href="@Url.Action("Index","Shop", new { catId= category.id})">@category.name</a>
                            }
                        </div>
                    </div><!-- /.widget -->
                </div><!-- /.sidebar -->
            </div><!-- /.col-md-3 -->
            <div class="col-md-9">
                <div class="filter-shop clearfix">
                    <p class="showing-product float-right">
                        Showing 1–12 of 56 Products
                    </p>
                </div><!-- /.filte-shop -->
            <div id="divProduct">
                @{ 
                    var filterPro = new FilterShop();
                    filterPro.products = Model.Products;
                    Html.RenderPartial("FilterIndex", filterPro);
                }
            </div>
                <div class="product-pagination text-center clearfix">
                    <ul class="flat-pagination">
                        <li class="prev">
                            <a href="#"><i class="fa fa-angle-left"></i></a>
                        </li>
                        <li><a href="#">1</a></li>
                        <li class="active"><a href="#" title="">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                    </ul><!-- /.flat-pagination -->
                </div>
            </div><!-- /.col-md-9 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section><!-- /.flat-row -->
<script>
    var callTimeout;
    var priceSlider = $("#slide-range").slider({
        range: true,
        min: 0,
        max: @Model.maxPrice ,
        values: [0,@Model.maxPrice],
        slide:function(event,ui){
            var minPrice=ui.values[0];
            var maxPrice=ui.values[1];
            $("#amount").val("₹"+minPrice+".00"+" - "+"₹"+maxPrice+".00");
            clearTimeout(callTimeout);
            callTimeout=setTimeout(GetData,2000)
        }});
    function GetData(minprice ,maxprice){
        console.log("GetData call!")
        $.ajax({
            url:'@Url.Action("FilterIndex", "Shop")',
            data:{
                minPrice: priceSlider.slider("values",0),
                maxPrice: priceSlider.slider("values",1)
            },
            success: function (response) {
                $("#divProduct").html(response);
            },
            error: function (err) {
                console.log("Fail!");
            }})
        
            };
</script>